# .github/workflows/notify-update.yml
name: Notify Update

on:
  push:
    branches:
      - main

jobs:
  call-uri:
    runs-on: ubuntu-latest
    steps:
      - name: Call update endpoint
        run: |
          curl -X POST https://void-tool.onrender.com/Health/restart
